### PR TITLE
Update osgi jar link

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Update osgi jar link
- Depends: https://github.com/eclipse/openj9/pull/11520
- Related: https://github.com/AdoptOpenJDK/run-aqa/issues/62

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links (Grinder_TKG):
jdk 11: xlinux 1039  aix 1040  zos 1042
jdk 8: xlinux 1043   aix 1044  win 1045

Download successfully with the updated link and sha:
```
12:09:04       [exec] downloading dependent third party jars to /home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/lib
12:09:04       [exec] downloading  https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.osgi/3.16.100/org.eclipse.osgi-3.16.100.jar
12:09:04       [exec] --> file downloaded to /home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/lib/org.eclipse.osgi-3.16.100.jar
12:09:04       [exec] downloaded dependent third party jars successfully
```

**Comment by LongyuZhang** [comment]
@llxia @renfeiw Could you review it? Thanks.

**Comment by sophia-guo** [comment]
Should test in openj9 be updated tar name has been changed? https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/CDSAdaptorTest/cdsadaptortest.xml#L34

**Comment by LongyuZhang** [comment]
> Should test in openj9 be updated as tar name has been changed? https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/CDSAdaptorTest/cdsadaptortest.xml#L34

It is in another PR: https://github.com/eclipse/openj9/pull/11520

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
I would suggest using a generic name (i.e., org.eclipse.osgi.jar) next time so that we do not need to update the name in multiple repos.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
https://ci.eclipse.org/openj9/job/test.getDependency/12611/ passed

**Pull request merged**
