### PR TITLE
Disable Mode650 on 32-bit platforms

### PR DESCRIPTION
**Pull request by llxia**
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Should Mode150 be disabled as well? The Mode150 is skipped for now for hotspot with spec set as without suffix  _mixed. With the plan to enabled Mode150 for hotspot later the same issue will be hit https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137#issuecomment-758167085?

**Comment by llxia** [comment]
Mode150 is disabled on 32-bit platforms

**Comment by llxia** [comment]
|Target|Impl|Platform|Grinder|
|--|--|--|--|
|sanity.openjdk|openj9|x86-64_linux| https://ci.adoptopenjdk.net/job/Grinder_TKG/99|
|sanity.openjdk|hotspot|x86-64_linux| https://ci.adoptopenjdk.net/job/Grinder_TKG/100|
|sanity.openjdk|hotspot|x86-32_windows| https://ci.adoptopenjdk.net/job/Grinder_TKG/101|
|sanity.openjdk|openj9|x86-32_windows| https://ci.adoptopenjdk.net/job/Grinder_TKG/102|
|sanity.openjdk|hotspot|x86-64_windows| https://ci.adoptopenjdk.net/job/Grinder_TKG/103|
|sanity.openjdk|openj9|x86-64_windows| https://ci.adoptopenjdk.net/job/Grinder_TKG/104|
|sanity.openjdk|openj9|x86-64_windows_xl| https://ci.adoptopenjdk.net/job/Grinder_TKG/106|

**Comment by llxia** [comment]
The plan to add new NoOptions to run on 32bit only (in another PR)

**Review by smlambert — APPROVED** [review]

**Pull request merged**
