### PR TITLE
Add a macro to conditionally set properties.

### PR DESCRIPTION
**Pull request by sophia-guo**
Conditionally set properties based on whether or not another property is
set to a non-empty value.

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Related with https://github.com/AdoptOpenJDK/openjdk-tests/issues/2181#issuecomment-765468523 . 

Ant `isset` doesn't check if the property is empty. This is to enhance the` isset `check to check `isset` as a non-empty value, which fixes the issues when the environment variable is set as empty. 

Tested with openjdk tests using dynamic agent.
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/245/

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
@sophia-guo - did you run any regular Grinders to ensure no unexpected behaviour (where build.xml files were is-setting?)

**Comment by sophia-guo** [comment]
Thanks for reminding @smlambert !

Grinder with TKG and JDK_REPO as empty : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/165/console

Regular grinder without the choice of combination of TKG_OWNER_BRANCH and JDK_REPO( JDK_BRANCH) parameters. Tested in https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/245/ and https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/269/

**Pull request merged**
