### PR TITLE
Add column linux_x86-64_mxdptrs in ottawa.csv

### PR DESCRIPTION
**Pull request by renfeiw**
- add column H linux_x86-64_mxdptrs
- use fx=IF(OR($F7="yes", $G7="yes"), "yes", "no") for mode value H7
- apply fx for other mode values

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
internal grinder: Grinder_TKG/977

**Comment by llxia** [comment]
Could you resolve the conflicts? Thanks

**Comment by renfeiw** [comment]
Updated, new internal grinder: Grinder_TKG/979

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
