### PR TITLE
Update TRSS api

### PR DESCRIPTION
**Pull request by OscarQQ**
fixes: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/243
together with this PR https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/244
[ci skip]

Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Since this can only be tested locally, could you paste the local test output? Thanks

**Comment by OscarQQ** [comment]
```
Attempting to get test duration data from TRSS:
curl --silent --max-time 120 localhost:3001/api/getTestAvgDuration?limit=10&jdkVersion=11&impl=j9&platform=x86-64_mac&group=functional&level=sanity

TEST DURATION
====================================================================================
Total number of tests searched: 1598
No test duration data found.
(Default duration assigned, executed tests: 40s; skipped/disabled tests: 0s.)
====================================================================================


Test target is split into 3 lists.
-------------------------------------testList_0-------------------------------------
Number of tests: 534
********
```
No error is thrown [here](https://github.com/OscarQQ/TKG/blob/dcc5551f93d206699bda89987d518834c0a349b9/src/org/testKitGen/TestDivider.java#L241) and json is successfully parsed

**Comment by llxia** [comment]
Did you have data by using localhost:3001/api/getTestAvgDuration?limit=10&jdkVersion=11&impl=j9&platform=x86-64_mac&group=functional&level=sanity?

**Comment by OscarQQ** [comment]
Sorry I didn't use openjdk group , here is the updated test output
```
Modes data parsed from resources/modes.xml and resources/ottawa.csv.

Attempting to get test duration data from TRSS:
curl --silent --max-time 120 localhost:3001/api/getTestAvgDuration?limit=10&jdkVersion=11&impl=j9&platform=x86-64_mac&group=openjdk&level=sanity

TEST DURATION
====================================================================================
Total number of tests searched: 7
Number of test durations found: 7
Top slowest tests: 
        41m38s jdk_lang_j9_0
        32m58s jdk_util_j9_0
        09m23s jdk11_tier1_pack200_0
====================================================================================

Test target is split into 3 lists.
Reducing estimated test running time from 92m48s to 41m38s.

-------------------------------------testList_0-------------------------------------
Number of tests: 1
Estimated running time: 41m38s
TESTLIST=jdk_lang_j9_0
******
```

**Comment by llxia** [comment]
TRSS server is updated: https://trss.adoptopenjdk.net/api/getTestAvgDuration?platform=x86-64_linux&level=sanity&group=openjdk&jdkVersion=8&impl=j9&numMachines=3

**Pull request merged**
