### PR TITLE
Add feature to disable vendor

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
tested in internal grinder: Grinder_TKG/1146, Grinder_TKG/1147
external grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/166/ (with disabled vendor playlist in openj9)

**Comment by llxia** [comment]
Above Grinder failed due to missing end-tag "</disabled>" in playlist.xml

```00:02:47.080  [Fatal Error] playlist.xml:816:4: The element type "disabled" must be terminated by the matching end-tag "</disabled>".
00:02:47.080  org.xml.sax.SAXParseException; systemId: file:/C:/Users/jenkins.EC2AMAZ-LDA73k6/workspace/Grinder_TKG/openjdk-tests/TKG/../functional/Java8andUp/playlist.xml; lineNumber: 816; columnNumber: 4; The element type "disabled" must be terminated by the matching end-tag "</disabled>".
```

**Comment by renfeiw** [comment]
> Above Grinder failed due to missing `end-tag "</disabled>"` in playlist.xml
> 
> ```
> 00:02:47.080  org.xml.sax.SAXParseException; systemId: file:/C:/Users/jenkins.EC2AMAZ-LDA73k6/workspace/Grinder_TKG/openjdk-tests/TKG/../functional/Java8andUp/playlist.xml; lineNumber: 816; columnNumber: 4; The element type "disabled" must be terminated by the matching end-tag "</disabled>".
> ```

Updated the grinder link, the problem should be solved now.

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
