### PR TITLE
Update machineInfo detection

### PR DESCRIPTION
**Pull request by renfeiw**
- encapsulate detected info into Class
- add assertion for some of the prerequisites

Signed-off-by: renfeiw renfeiw@ca.ibm.com

### CODE REVIEW

**Comment by renfeiw** [comment]
Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/163, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/164
internal grinder: Grinder_TKG/1144

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
I noticed while looking at the Grinders you launched that https://github.com/AdoptOpenJDK/TKG/blob/master/src/org/openj9/envInfo/MachineInfo.java#L35 does not work for osx, from a [quick query](https://stackoverflow.com/questions/1715580/how-to-discover-number-of-logical-cores-on-mac-os-x), looks like you can use `sysctl -n hw.ncpu`.  Can be addressed in a separate PR (since its previous code, and does not affect this PR).

From Grinder_TKG/163:

```
22:14:52  cpuCores : 
22:14:52  	cat: /proc/cpuinfo: No such file or directory
22:14:52  	       0
```

**Comment by renfeiw** [comment]
> I noticed while looking at the Grinders you launched that https://github.com/AdoptOpenJDK/TKG/blob/master/src/org/openj9/envInfo/MachineInfo.java#L35 does not work for osx, from a [quick query](https://stackoverflow.com/questions/1715580/how-to-discover-number-of-logical-cores-on-mac-os-x), looks like you can use `sysctl -n hw.ncpu`. Can be addressed in a separate PR (since its previous code, and does not affect this PR).
> 
> From Grinder_TKG/163:
> 
> ```
> 22:14:52  cpuCores : 
> 22:14:52  	cat: /proc/cpuinfo: No such file or directory
> 22:14:52  	       0
> ```

Thanks for pointing out. I will address this in a separate issue. Looks like it might be helpful to have a way to specify different commands for different platforms.

**Pull request merged**
