### PR TITLE
Enable DF flag diagnostic check

### PR DESCRIPTION
**Pull request by liqunl**
Also set silent JIT ENV such that no message will be printed out

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@smlambert May I ask for your review?

**Comment by smlambert** [comment]
Grinders:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/31 (xlinux/jdk8/hs)
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/32 (win64/jdk11/j9)

**Comment by liqunl** [comment]
The windows failure seems to be infra issue. It's not able to get a file on the machine. I started another windows grinder
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/33

**Comment by smlambert** [comment]
All kinds of trouble running a Grinder on windows machines today...

17:43:35  getOpenjdk:
17:43:35       [exec] error: could not lock config file /etc/gitconfig: Permission denied
17:43:35       [exec] Result: 255
17:43:35       [echo] git clone --depth 1 -q  https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
17:45:49       [exec] Check sha in openjdk-jdk and store the info in C:/Users/jenkins/workspace/Grinder_TKG/openjdk-tests//TKG/SHA.txt

**Comment by smlambert** [comment]
Since there is no way those changes are related to your TKG PR, I will run on a different platform (just to audit j9 and something other than xlinux)

**Comment by liqunl** [comment]
@smlambert Did you run test on different platforms? Is the result good?

**Comment by smlambert** [comment]
Yes, apologies, I launched it and never got back to the PR to merge.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/35/

**Review by smlambert — APPROVED** [review]

**Pull request merged**
