### PR TITLE
Shorten test_output folder name to output

### PR DESCRIPTION
**Pull request by renfeiw**
Correct PR to replace https://github.com/AdoptOpenJDK/TKG/pull/132

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
This is a proactive measure in TKG. Some system tests generate unnecessary long paths. The overall path > MAX_PATH limit on Windows. While we shortened the system test path, we are trying to shorten the path in TKG to avoid similar breakage.

**Comment by renfeiw** [comment]
Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/154, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/155

**Comment by renfeiw** [comment]
related PR: AdoptOpenJDK/openjdk-tests#2118

**Review by smlambert — APPROVED** [review]
Thanks for the quick redo @renfeiw !

**Review by llxia — APPROVED** [review]

**Pull request merged**
