### PR TITLE
remove get all dependency at the beginning

### PR DESCRIPTION
**Pull request by OscarQQ**
closed: https://github.com/AdoptOpenJDK/TKG/issues/63
Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
Grinder_TKG/1007/   `x86-64_linux` target: all
Grinder_TKG/1008/   `x86-64_windows` target: all

**Comment by llxia** [comment]
This PR cannot be delivered until openj9jtregtimeouthandler.jar is updated. Please see https://github.com/AdoptOpenJDK/TKG/issues/63#issuecomment-645437494

**Comment by llxia** [comment]
Could we also test this locally? Or test in Grinder by removing getDependencies code from Jenkins script? Thanks

**Comment by OscarQQ** [comment]
yes, the link above uses my own openjdk at feature7 to exclude the jar https://github.com/OscarQQ/openjdk-tests/commit/a94b2b6974aaa413cc627e25b3515a9cc101f404, they will mimic the local test environment

**Comment by llxia** [comment]
ah, I was looking at a wrong Grinder. Thanks @OscarQQ

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
