### PR TITLE
Remove platform specific code in getDependencies script

### PR DESCRIPTION
**Pull request by nikolamilijevic1**
-removes platform specific code
-no longer use wget, only curl

resolves: #68
signed-off-by: nikolamilijevic 1 <nmilijev@uwaterloo.ca>

### CODE REVIEW

**Comment by nikolamilijevic1** [comment]
tested internally:
| BUILD | PLATFORM | TARGET  | BUILD_LIST |
--- | --- | --- |  --- |
| Grinder_TKG/540 | x86-64_linux | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/541 | x86-64_mac | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/542 | x86-32_windows | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/543 | s390x_linux | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/555 | x86-64_linux | sanity | functional |
| Grinder_TKG/556 | s390x_zos | sanity | functional/Java8andUp |

**Comment by nikolamilijevic1** [comment]
@llxia @renfeiw could you review this please

**Comment by llxia** [comment]
Did the above Ginder links get updated? I still see `rm: cannot remove ` error.

**Comment by nikolamilijevic1** [comment]
tested internally:
| BUILD | PLATFORM | TARGET  | BUILD_LIST |
--- | --- | --- |  --- |
| Grinder_TKG/562 | x86-64_linux | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/563 | x86-64_mac | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/564 | x86-32_windows | floatSanityTests | functional/Java8andUp |
| Grinder_TKG/566 | s390x_linux | floatSanityTests | functional/Java8andUp |

**Comment by nikolamilijevic1** [comment]
@llxia I updated the tests that gave `rm: cannot remove`, the error seems fixed

**Comment by llxia** [comment]
Thanks for the updates @nikolamilijevic1

**Comment by renfeiw** [comment]
Thanks @nikolamilijevic1 !

**Pull request merged**
