### PR TITLE
Add check if repo directory exists

### PR DESCRIPTION
**Pull request by sophia-guo**
There are cases that expected repo_dir doesn't exist. Add the check to ensure SHA information is correct.

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Migrate from https://github.com/eclipse/openj9/pull/7843

**Comment by llxia** [comment]
I would like to hold this PR until https://github.com/eclipse/openj9/pull/7885 and AdoptOpenJDK/openjdk-tests#1472 are merged

**Comment by sophia-guo** [comment]
@llxia  as eclipse/openj9#7885 and AdoptOpenJDK/openjdk-tests#1472 are merged, could you take a review of this?

**Comment by llxia** [comment]
Could you run a test using Grinder_TKG again? Thanks

**Comment by sophia-guo** [comment]
Positive grinder:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/979/
Negative grinder:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/981/

**Pull request merged**
