### PR TITLE
Shorten test_output folder name to output

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
internal grinder: Grinder_TKG/1030

**Comment by llxia** [comment]
This is a proactive measure in TKG. [Some system tests](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2109) generate unnecessary long paths. The overall path > MAX_PATH limit on Windows. While we shortened the system test path, we are trying to shorten the path in TKG to avoid similar breakage.

**Comment by llxia** [comment]
Also, the Jenkins script needs to be updated. For example, https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L629

**Comment by renfeiw** [comment]
related PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2118

**Comment by renfeiw** [comment]
Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/149/

**Comment by llxia** [comment]
Could we run a failed test to verify that `output_*` can be archived correct?

**Comment by renfeiw** [comment]
> Could we run a failed test to verify that `output_*` can be archived correct?

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/151/ failed in compilation, the archive contains output_compilation.

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @renfeiw !

**Pull request merged**
